export const funnyCat = [
    {
        title: 'Hanger-Cat',
        url: 'https://i.ytimg.com/vi/qTmjKpl2Jk0/maxresdefault.jpg',
        description: 'A cat in a hanger',
        key: 1,
        rate: 5,
    },
    {
        title: 'Beluga',
        url: 'https://i.pinimg.com/736x/ea/0b/36/ea0b36dfa8e14f15b515bc469070de06.jpg',
        description: 'The annoying cat of Discord',
        key: 2,
        rate: 1,
    },
    {
        title: 'Cutie-Cat',
        url: 'https://i.pinimg.com/736x/ba/92/7f/ba927ff34cd961ce2c184d47e8ead9f6.jpg',
        description: 'A very cute cat',
        key: 3,
        rate: 8,
    },
    {
        title: 'Selfie-Cat & Friend',
        url: 'https://static.wikia.nocookie.net/6bae471b-943d-4d3f-85e7-280ba3483ec5',
        description: 'A cat who take selfie with friend',
        key: 4,
        rate: 9,
    },
    {
        title: 'Cat in distress',
        url: 'https://ngolongtech.b-cdn.net/wp-content/uploads/2016/05/ngolongtech_Top-funny-cats-picture-3.jpg',
        description: 'A cat who dont like to be wash',
        key: 5,
        rate: 6,
    },
    {
        title: 'Selfie-Cat low angle',
        url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT2tiRUxxzj86e-mouwXvUZoEZaRWgzvwpFLw&usqp=CAU',
        description: 'A cat who take selfie in a wierd angle',
        key: 6,
        rate: 5,
    },
    {
        title: 'Cat vs the cucumber gang',
        url: 'https://i.ytimg.com/vi/eX2qFMC8cFo/maxresdefault.jpg',
        description: 'A cat surrounded by cucumbers',
        key: 7,
        rate: 2,
    },
    {
        title: 'Fear',
        url: 'https://i.redd.it/25s04u40uqy11.jpg',
        description: 'A very scared cat',
        key: 8,
        rate: 8,
    },
    {
        title: 'Jumping-Cat',
        url: 'https://i.pinimg.com/originals/06/3f/9c/063f9cc7781e88052b1b9d97599e1a73.jpg',
        description: 'A cat who jumps very high',
        key: 9,
        rate: 6,
    },
    {
        title: 'Hidden kitten',
        url: 'https://valevets.com/wp-content/uploads/2014/08/kitten1.jpg',
        description: 'A kitten hidding in jeans',
        key: 10,
        rate: 3,
    },
];